import { useMemo } from 'react';
import { useApp, colors } from '../../app/context';
import { taskSegment,layoutTimeline,snapMinute } from '../../domain/timeline';
import { dateOf } from '../../domain/rules';
import { GoogleEvents } from '../integrations/GoogleEvents';
export function Timeline({start,select}:{start:number;select:(day:number)=>void}) {
 const {snapshot:s,repo,run,open,quick,t,preferences:p}=useApp();
 const tasks=useMemo(()=>s.tasks.filter(x=>!x.is_template&&!x.is_skipped&&!x.is_completed),[s.tasks]);
 const clock=(m:number)=>`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;
 return <div className="timeline-scroll"><div className="timeline-week"><div className="timeline-labels"><div className="timeline-heading"/>{Array.from({length:24},(_,h)=><span key={h} style={{top:116+h*60}}>{clock(h*60)}</span>)}</div>{Array.from({length:7},(_,i)=>start+i).map(day=>{
 const timed=layoutTimeline(tasks.flatMap(task=>{const segment=taskSegment(task,day);return segment?[segment]:[]}));
 return <section key={day} className="timeline-day"><div className="timeline-heading"><button onClick={()=>select(day)}>{dateOf(day).toLocaleDateString(p.language,{weekday:'short',day:'numeric',timeZone:'UTC'})}</button><button aria-label={t('add')} onClick={()=>quick({due_day:day})}>+</button><div className="timeline-allday">{tasks.filter(x=>x.due_day===day&&x.minute_of_day===null).map(task=><button key={task.id} draggable onDragStart={e=>e.dataTransfer.setData('text/pcix-task',task.id)} onClick={()=>open(task.id)}>{task.title}</button>)}<GoogleEvents day={day}/></div></div>
 <div className="timeline-hours" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const task=tasks.find(x=>x.id===e.dataTransfer.getData('text/pcix-task'));if(!task)return;const rect=e.currentTarget.getBoundingClientRect();const minute=snapMinute(e.clientY-rect.top,rect.height);void run(()=>repo.saveTask({...task,due_day:day,minute_of_day:minute,duration_minutes:task.minute_of_day===null?30:task.duration_minutes}));}} onDoubleClick={e=>{if(e.target!==e.currentTarget)return;const rect=e.currentTarget.getBoundingClientRect();quick({due_day:day,minute_of_day:snapMinute(e.clientY-rect.top,rect.height),duration_minutes:30});}}>
 {timed.map(item=>{const task=tasks.find(x=>x.id===item.id)!;return <div className="timeline-event" key={item.id} style={{top:item.start,height:Math.max(18,item.end-item.start),left:`${item.lane/item.columns*100}%`,width:`${100/item.columns}%`,borderColor:colors[(s.lists.find(l=>l.id===task.list_id)?.color??0)%12]}} draggable onDragStart={e=>e.dataTransfer.setData('text/pcix-task',task.id)}><button onClick={()=>open(task.id)}><small>{clock(item.start)}</small> {task.title}</button><button className="resize-event" aria-label={t('resizeDuration')} onPointerDown={e=>{e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);e.currentTarget.dataset.startY=String(e.clientY);}} onPointerUp={e=>{const y=Number(e.currentTarget.dataset.startY);if(!Number.isFinite(y))return;const delta=Math.round((e.clientY-y)/15)*15;void run(()=>repo.saveTask({...task,duration_minutes:Math.min(525600,Math.max(15,(task.duration_minutes??30)+delta))}));}} onKeyDown={e=>{if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();void run(()=>repo.saveTask({...task,duration_minutes:Math.max(15,(task.duration_minutes??30)+(e.key==='ArrowDown'?15:-15))}));}} draggable={false}>↕</button></div>})}
 </div></section>})}</div></div>;
}
