"""Generate Android vectors/catalog from the pinned official Lucide source checkout.
Usage: python3 tools/import_lucide.py /path/to/lucide
"""
import sys, json, re, shutil
from pathlib import Path
import xml.etree.ElementTree as E
from xml.sax.saxutils import escape, quoteattr
from svg_path import normalize_path
src=Path(sys.argv[1]); root=Path(__file__).resolve().parents[1]
res=root/'app/src/main/res'; out=root/'app/src/main/java/com/example/pix/ui/LucideCatalog.kt'
labels=[]; entries=[]
def path(e):
 a=e.attrib; tag=e.tag.split('}')[-1]
 def n(key, default=0):return float(a.get(key,default))
 if tag=='path':return a['d']
 if tag=='line':return f'M{n("x1")},{n("y1")} L{n("x2")},{n("y2")}'
 if tag in ('circle','ellipse'):
  x,y=n('cx'),n('cy'); rx=n('r') if tag=='circle' else n('rx');ry=n('r') if tag=='circle' else n('ry')
  return f'M{x-rx},{y} a{rx},{ry} 0 1,0 {2*rx},0 a{rx},{ry} 0 1,0 {-2*rx},0'
 if tag=='rect':
  x,y,w,h=n('x'),n('y'),n('width'),n('height');rx=min(n('rx',a.get('ry',0)),w/2);ry=min(n('ry',a.get('rx',0)),h/2)
  if not rx or not ry:return f'M{x},{y} h{w} v{h} h{-w} Z'
  return f'M{x+rx},{y} H{x+w-rx} A{rx},{ry} 0 0 1 {x+w},{y+ry} V{y+h-ry} A{rx},{ry} 0 0 1 {x+w-rx},{y+h} H{x+rx} A{rx},{ry} 0 0 1 {x},{y+h-ry} V{y+ry} A{rx},{ry} 0 0 1 {x+rx},{y} Z'
 if tag in ('polyline','polygon'):return 'M'+a['points']+(' Z' if tag=='polygon' else '')
 raise ValueError(tag)
for f in sorted((src/'icons').glob('*.svg')):
 name=f.stem; key='lucide_'+name.replace('-','_'); svg=E.parse(f).getroot()
 assert svg.get('viewBox')=='0 0 24 24'
 body=[]
 for e in svg:
  fill='#FF000000' if e.get('fill')=='currentColor' else '#00000000'
  assert e.get('fill') in (None,'none','currentColor')
  body.append(f'<path android:fillColor="{fill}" android:strokeColor="#FF000000" android:strokeWidth="2" android:strokeLineCap="round" android:strokeLineJoin="round" android:pathData={quoteattr(normalize_path(path(e)))}/>')
 (res/'drawable'/f'{key}.xml').write_text('<!-- Lucide: see assets/licenses/lucide.txt -->\n<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="24dp" android:height="24dp" android:viewportWidth="24" android:viewportHeight="24">\n'+'\n'.join(body)+'\n</vector>\n')
 labels.append(f'<string name="{key}" translatable="false">{escape(name.replace("-"," ").capitalize())}</string>')
 meta=json.loads(f.with_suffix('.json').read_text()); tags=' '.join([name.replace('-',' ')]+meta.get('tags',[])+meta.get('categories',[]))
 entries.append(f'    LucideEntry("{name}", R.drawable.{key}, R.string.{key}, {json.dumps(tags,ensure_ascii=False)}),')
(res/'values/lucide_labels.xml').write_text('<resources>\n'+'\n'.join(labels)+'\n</resources>\n')
chunks=[entries[i:i+80] for i in range(0,len(entries),80)]
out.write_text('''// Generated by tools/import_lucide.py. Source and license: assets/licenses/lucide.txt
package com.example.pix.ui
import com.example.pix.R

data class LucideEntry(val name: String, val drawable: Int, val label: Int, val keywords: String) {
    val id: String get() = "lucide:$name"
}
object LucideCatalog {
    val entries: List<LucideEntry> by lazy { listOf('''+','.join(f'part{i}()' for i in range(len(chunks)))+''').flatten() }
    val byId by lazy { entries.associateBy { it.id } }
}
'''+ '\n'.join('private fun part'+str(i)+'() = listOf(\n'+'\n'.join(chunk)+'\n)\n' for i,chunk in enumerate(chunks)))
license_dir=root/'app/src/main/assets/licenses';license_dir.mkdir(parents=True,exist_ok=True)
shutil.copyfile(src/'LICENSE',license_dir/'lucide.txt')
print('Generated',len(entries),'icons')
